# Generated by Django 4.2.4 on 2023-09-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0002_rename_announcement_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(choices=[('TA', 'Tanks'), ('HI', 'Healers'), ('DD', 'Damage Dealers'), ('TR', 'Traders'), ('GM', 'Guild Master'), ('QG', 'Quest Givers'), ('BS', 'Blacksmiths'), ('LW', 'Leatherworkers'), ('PM', 'Potion Makers'), ('SM', 'Spell Masters')], max_length=2, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_content',
            field=models.FileField(blank=True, null=True, upload_to='media/other_media/', verbose_name='Медиа'),
        ),
    ]
