# Generated by Django 4.2.4 on 2023-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0005_alter_comment_author_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(choices=[('TA', 'Tanks'), ('HI', 'Healers'), ('DD', 'Damage Dealers'), ('TR', 'Traders'), ('GM', 'Guild Master'), ('QG', 'Quest Givers'), ('BS', 'Blacksmiths'), ('LW', 'Leatherworkers'), ('PM', 'Potion Makers'), ('SM', 'Spell Masters')], max_length=2, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_content',
            field=models.FileField(blank=True, null=True, upload_to='other_media/', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
