# Generated by Django 4.2.4 on 2023-09-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0006_alter_category_slug_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
