# Generated by Django 4.2.4 on 2023-09-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0007_comment_is_accept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_accept',
            new_name='is_accepted',
        ),
    ]
