# Generated by Django 4.2.4 on 2023-09-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0009_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
